#!/bin/bash

if [[ -z $RPC_PARAM_TEXT ]] 
then
	printf "Missing \"text\" param" > /dev/stderr
	exit -1
fi

read -r -d '' RPC_OUTPUT << EOT
{ 
   "echo back": "${RPC_PARAM_TEXT}",
   "user": "${RPC_USER}",
   "log_folder": "${LOG_FOLDER}"
}
EOT

printf "${RPC_OUTPUT}"
exit 0;

